src/objects/Sub_ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsDone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ToDo__c</fullName>
        <label>ToDo</label>
        <referenceTo>ToDo__c</referenceTo>
        <relationshipLabel>Sub-ToDos</relationshipLabel>
        <relationshipName>Sub_ToDos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubToDoDtoMapper.cls
public with sharing class SubToDoDtoMapper {

    public static SubToDoDto mapSubToDoToDto(Sub_ToDo__c subToDo){
        SubToDoDto dto = new SubToDoDto();
        dto.id = subToDo.Id;
        dto.relatedToDo = subToDo.ToDo__c;
        dto.name = subToDo.Name;
        dto.description = subToDo.Description__c;
        dto.isDone = subToDo.IsDone__c;

        return dto;
    }

    public static List<SubToDoDto> mapSubToDosListToDtosList(List<Sub_ToDo__c> subToDos){
        List<SubToDoDto> dtos = new List<SubToDoDto>();
        for (Sub_ToDo__c subToDo: subToDos){
            dtos.add(mapSubToDoToDto(subToDo));
        }
        return dtos;
    }

    public static List<Id> mapSubToDosListToIdsList(List<Sub_ToDo__c> subToDos){
        List<Id> ids = new List<Id>();
        for (Sub_ToDo__c subToDo: subToDos){
            ids.add(subToDo.Id);
        }

        return ids;
    }

}