src/objects/Sub_ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ToDo__c</fullName>
        <label>ToDo</label>
        <referenceTo>ToDo__c</referenceTo>
        <relationshipLabel>Sub-ToDos</relationshipLabel>
        <relationshipName>Sub_ToDos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubToDoControllerTest.cls
@IsTest
private class SubToDoControllerTest {

    public static Integer subToDoListSize = 2;

    @TestSetup
    static void setUp(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('OauthStaticResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

        ToDo__c todo = new ToDo__c(Name='Hello', Description__c='World');
        insert todo;
        Sub_ToDo__c subToDo1 = new Sub_ToDo__c(Name='One', ToDo__c = todo.Id);
        insert subToDo1;
        Sub_ToDo__c subToDo2 = new Sub_ToDo__c(Name='Two', ToDo__c = todo.Id);
        insert subToDo2;

    }

    @IsTest
    static void getSubToDoListByParentToDoIdShouldReturnRelatedSubToDosList() {
        Id todoId = [SELECT Id FROM ToDo__c].get(0).Id;

        Test.startTest();
        List<Sub_ToDo__c> result = SubToDoController.getSubToDoListByParentToDoId(todoId);
        Test.stopTest();
        System.assertEquals(subToDoListSize, result.size());
    }
}