src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ToDo_Status</valueSetName>
        </valueSet>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <recordTypes>
        <fullName>Personal</fullName>
        <active>true</active>
        <description>My personal Todo</description>
        <label>Personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ToDo_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
        <default>true</default>
        <label>Planned</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>ToDo Status</masterLabel>
</GlobalValueSet>

src/classes/ToDoLControllerTest.cls
@IsTest
private class ToDoLControllerTest {

    @TestSetup
    static void setUp() {
        ToDo__c toDo1 = new ToDo__c(
                Name = 'Test',
                Description__c = 'Description',
                Category__c = 'Personal',
                Status__c = 'Planned',
                Start_Date__c = Date.today(),
                Deadline__c = Date.today() + 1
        );

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('OauthStaticResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

        insert toDo1;
    }

    @IsTest
    static void getToDoListShouldReturnToDoList() {
        ToDo__c toDo1 = [SELECT Id FROM ToDo__c WHERE Name = 'Test'];

        Test.startTest();
        List<ToDo__c> results = ToDoController.getToDoList();
        Test.stopTest();

        System.assert(results != null);
        for (ToDo__c result: results){
            System.assertEquals(toDo1.Id, result.Id);

        }

    }
}