src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ToDo_Status</valueSetName>
        </valueSet>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ToDo_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
        <default>true</default>
        <label>Planned</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>ToDo Status</masterLabel>
</GlobalValueSet>

src/classes/ToDoDtoMapper.cls
public with sharing class ToDoDtoMapper {

    public static ToDoDto mapToDoToDto(ToDo__c toDo) {
        ToDoDto dto = new ToDoDto();
        dto.id = toDo.Id;
        dto.name = toDo.Name;
        dto.description = toDo.Description__c;
        dto.status = toDo.Status__c;
        dto.category = toDo.Category__c;
        dto.startDate = toDo.Start_Date__c;
        dto.deadline = toDo.Deadline__c;
        dto.recordTypeName = [SELECT Name FROM RecordType WHERE Id = :toDo.RecordTypeId].Name;

        return dto;
    }

    public static List<ToDoDto> mapToDosListToDtoList(List<ToDo__c> toDos){
        List<ToDoDto> dtos = new List<ToDoDto>();

        for (ToDo__c todo: toDos){
            ToDoDto dto = mapToDoToDto(todo);
            dtos.add(dto);
        }
        return dtos;
    }

    public static List<Id> mapToDosListToIdsList(List<ToDo__c> todos){
        List<Id> ids = new List<Id>();

        for (ToDo__c todo: todos){
            ids.add(todo.Id);}

        return ids;
    }

}