src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ToDo_Status</valueSetName>
        </valueSet>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <recordTypes>
        <fullName>Personal</fullName>
        <active>true</active>
        <description>My personal Todo</description>
        <label>Personal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ToDo_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
        <default>true</default>
        <label>Planned</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>ToDo Status</masterLabel>
</GlobalValueSet>

src/classes/BatchableCleanTodoTest.cls
/**
 * Created by Bogdan on 28.10.2020.
 */

@IsTest
public with sharing class BatchableCleanTodoTest {

    @TestSetup
    static void setUp(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('OauthStaticResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        createTestRecord();
        createTestRecord();
    }

    @IsTest
    static void testBatchDeleteOldTodo() {
        List<ToDo__c> todos = [SELECT Id FROM ToDo__c];
        System.assert(todos.size() == 2);

        Test.startTest();
        BatchableCleanTodo batchableCleanTodo = new BatchableCleanTodo();
        Database.executeBatch(batchableCleanTodo);
//        batchableCleanTodo.execute(null, todos);
        Test.stopTest();

        List<ToDo__c> todosAfterBatch = [SELECT Id FROM ToDo__c];
        System.assert(todosAfterBatch.size() == 0);
    }

    static ToDo__c createTestRecord() {
        ToDo__c testTodo = new ToDo__c(
                Name = 'Test record', Description__c = 'Test Batch Delete',
                Status__c = 'Canceled', Category__c = 'Personal',
                Start_Date__c = Date.today().addDays(-20),
                Deadline__c = Date.today().addDays(-10));
        insert testTodo;
        return testTodo;
    }
}