src/objects/ToDo__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ToDo_Status</valueSetName>
        </valueSet>
    </fields>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <recordTypes>
        <fullName>Personal</fullName>
        <active>true</active>
        <description>My personal Todo</description>
        <label>Personal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Work</fullName>
        <active>true</active>
        <description>Work, business todo</description>
        <label>Work</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/ToDo_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Planned</fullName>
        <default>true</default>
        <label>Planned</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <masterLabel>ToDo Status</masterLabel>
</GlobalValueSet>

src/classes/ToDoDtoMapperTest.cls
@IsTest(SeeAllData = true)
private class ToDoDtoMapperTest {

    public static ToDo__c todo = new ToDo__c(
            Name = 'ToDo 1',
            Description__c = 'This ToDo for testing 1',
            Start_Date__c = System.today(),
            Deadline__c = System.today() + 1,
            Status__c = 'Planned',
            Category__c = 'Work',
            Id = 'a0009000001BGNeAAO',
            RecordTypeId = Schema.SObjectType.ToDo__c.getRecordTypeInfosByName().get('Personal').getRecordTypeId()
    );


    @IsTest
    static void mapToDoToDtoShouldReturnDto() {
        ToDoDto todoDto = new ToDoDto();
        todoDto.id = todo.Id;
        todoDto.name = todo.Name;
        todoDto.description = todo.Description__c;
        todoDto.startDate = todo.Start_Date__c;
        todoDto.deadline = todo.Deadline__c;
        todoDto.status = todo.Status__c;
        todoDto.category = todo.Category__c;
        todoDto.recordTypeName = 'Personal';

        Test.startTest();
        ToDoDto result = ToDoDtoMapper.mapToDoToDto(todo);
        Test.stopTest();
        System.assertEquals(todoDto.id, result.id);
        System.assertEquals(todoDto.name, result.name);
        System.assertEquals(todoDto.description, result.description);
        System.assertEquals(todoDto.startDate, result.startDate);
        System.assertEquals(todoDto.deadline, result.deadline);
        System.assertEquals(todoDto.status, result.status);
        System.assertEquals(todoDto.category, result.category);
    }


    @IsTest
    static void mapToDosListToDtoListShouldReturnToDoDtosList() {
        ToDoDto todoDto = new ToDoDto();
        todoDto.id = todo.Id;
        todoDto.name = todo.Name;
        todoDto.description = todo.Description__c;
        todoDto.startDate = todo.Start_Date__c;
        todoDto.deadline = todo.Deadline__c;
        todoDto.status = todo.Status__c;
        todoDto.category = todo.Category__c;
        todoDto.recordTypeName = 'Personal';

        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);

        Test.startTest();
        List<ToDoDto> results = ToDoDtoMapper.mapToDosListToDtoList(todos);
        Test.stopTest();
        for (ToDoDto result : results) {
            System.assertEquals(todoDto.id, result.id);
            System.assertEquals(todoDto.name, result.name);
            System.assertEquals(todoDto.description, result.description);
            System.assertEquals(todoDto.startDate, result.startDate);
            System.assertEquals(todoDto.deadline, result.deadline);
            System.assertEquals(todoDto.status, result.status);
            System.assertEquals(todoDto.category, result.category);
        }

    }

    @IsTest
    static void mapToDosListToIdsListShouldReturnIdsList() {
        List<ToDo__c> todos = new List<ToDo__c>();
        todos.add(todo);

        Test.startTest();
        List<Id> results = ToDoDtoMapper.mapToDosListToIdsList(todos);
        Test.stopTest();
        for (Id result : results) {
            System.assertEquals(todo.Id, result);
        }
    }

}